### ISSUE TITLE
Add resolver to build.sbt files?

### ISSUE THREAD

**Issue by mushtaq** [oyvindberg/ScalablyTyped#13]
I often load the sources of libraries I depend on, just to understand the facade better. 

Each time while loading the project (say from r/react folder) in IntelliJ, I have to add to this line build.sbt.

```scala
resolvers += Resolver.bintrayRepo("oyvindberg", "ScalablyTyped")
```

Will be great if this can be done by default, so that I do not have to stash my changes before pulling the latest version of this repo.

**Comment by mushtaq** [comment]
Oh ok, I can also add it to the global file in ~/.sbt folder, which is a good enough workaround.

**Comment by oyvindberg** [comment]
Oh, that's an oversight, will add it for next time we break the encoding and publish everything :)
Thanks!

**Comment by oyvindberg** [comment]
Fixed, will publish tomorrow

**Comment by mushtaq** [comment]
Thank you!
