### ISSUE TITLE
Potential precendence bug in type parsing

### ISSUE THREAD

**Issue by littlenag** [oyvindberg/ScalablyTyped#24]
I'm trying to use the generated bindings for react-stripe-elements.

In trying to construct the StripeProvider, which is the main react component, I'm seeing something strange that looks like a bug in how operators are parsed. Specially in the precedence given to intersection and union types.

In order to construct the react component we have to supply Props. Here is what your bindings have for the type signature of those props:

      type StripeProviderProps = reactDashStripeDashElementsLib.Anon_ApiKey with (StripeProviderOptions | reactDashStripeDashElementsLib.Anon_ApiKeyStripe) with StripeProviderOptions

That's an odd signature and not easily satisfiable. Looking at the typescript definition it would likely have been generated from (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-stripe-elements/index.d.ts), I think there is a bug. Here is what typescript has:

	type StripeProviderProps = { apiKey: string; stripe?: never; } & StripeProviderOptions | { apiKey?: never; stripe: stripe.Stripe | null; } & StripeProviderOptions;

Playing with typescript that definition seems to parse as 

	type StripeProviderProps = ({ apiKey: string; stripe?: never; } & StripeProviderOptions) | ({ apiKey?: never; stripe: stripe.Stripe | null; } & StripeProviderOptions);

However the generator appears to parse it as:

	type StripeProviderProps = ({ apiKey: string; stripe?: never; }) & (StripeProviderOptions | ({ apiKey?: never; stripe: stripe.Stripe | null; }) & (StripeProviderOptions);

Which then explains the strange type signature we get in the bindings.

That parsing only makes sense if type operators & and | have the same precedence level. I'm pretty sure that is incorrect. While I am unable to find any concrete documentation, playing the in the typescript REPL confirms that & should bind more tightly than |.

**Comment by oyvindberg** [comment]
Thanks for the report. This is an area that I know i haven't verified sufficiently so this seems probable. Will check it out and report back :)

**Comment by oyvindberg** [comment]
So this was easy to confirm and fix. I will wait a few days to push it, because since it changes `stdLib` *everything* will be republish, and i batch such changes to avoid churn and deleting artifacts too frequently.

As a quick workaround you can always cast your way around this for now, and copy/paste/change the definitions which are wrong (it should only be this case in the stripe library)

**Comment by oyvindberg** [comment]
This is fixed and published now
