### ISSUE TITLE
antd-native openDrawer and closeDrawer

### ISSUE THREAD

**Issue by mcallisto** [oyvindberg/ScalablyTyped#28]
I am trying to implement the `Drawer` component, see https://rn.mobile.ant.design/components/drawer/

But in https://github.com/oyvindberg/ScalablyTyped/tree/master/a/ant-design__react-native I cannot find the `openDrawer` and `closeDrawer` methods. Shouldn't they be there?

**Comment by oyvindberg** [comment]
Follow the types from the [Drawer props](https://github.com/oyvindberg/ScalablyTyped/blob/master/a/ant-design__react-native/src/main/scala/typings/atAntDashDesignReactDashNative/esDrawerMod/DrawerNativeProps.scala#L28) - you'll end up [here](https://github.com/oyvindberg/ScalablyTyped/blob/master/b/bang88__react-native-drawer-layout/src/main/scala/typings/atBang88ReactDashNativeDashDrawerDashLayout/atBang88ReactDashNativeDashDrawerDashLayoutMod/DrawerLayout.scala) - in another library :)

**Comment by mcallisto** [comment]
Great, thank you :) I will try to make it work and add it to the demo.

**Comment by mcallisto** [comment]
Hmmm... I would need some help on this one.

The closer I get to something compilable is:

```
@react object App extends DrawerLayout {

  type Props = Unit

  val component = FunctionalComponent[Props] { _ =>

    Provider(ProviderProps(locale = PartialLocale(locale = "enUS")))(
      Drawer(DrawerProps(sidebar = ScrollView(List(ListProps())(
        ListItem(ListItemProps())("Menu 1"),
        ListItem(ListItemProps())("Menu 2"),
      )).toST))(
        Button(ButtonProps(onPress = _ => openDrawer()))("Open drawer"),
    )
  }
}
```

But:
```
[error] /.../src/main/scala/hello/world/App.scala:19:2: A Scala.js-defined JS object cannot directly extend a native JS trait.
[error] @react object App extends DrawerLayout {
```

Which is the correct approach to use the `openDrawer` method?

**Comment by oyvindberg** [comment]
It doesn't make sense to extend the class like that, read up on how react references work. The prop I highlighted above will give you an instance, and you can save it in a var and write callbacks based on that

**Comment by mcallisto** [comment]
Ok, I got it, and it's working :)

```
  val component = FunctionalComponent[Props] { _ =>
    val (isModalVisible, updateIsModalVisible) = useState(false)

    var y: default | Null = new default {}

    Provider(ProviderProps(locale = PartialLocale(locale = "enUS")))(
            Drawer(DrawerProps(
        drawerRef = x => y = x,
        sidebar = ScrollView(List(ListProps())(
          ListItem(ListItemProps())("Menu 1"),
          ListItem(ListItemProps())("Menu 2"),
        )).toST)
      )(
        Button(ButtonProps(onPress = _ => y.asInstanceOf[DrawerLayout].openDrawer()))("Open drawer"),
    )
  }

```

**Comment by mcallisto** [comment]
Added to the demo https://github.com/mcallisto/slinky-antd-native.g8/commit/9a4aae720e8102625e1ec697f9268cbaf1a6696f
